apiVersion: v1
kind: ConfigMap
metadata:
  name: &app-name go-worker-credit-cm
  namespace: test-a
  labels:
    app: *app-name
data:
  POD_NAME: "go-worker-credit"
  API_VERSION: "1.1"
  DB_HOST: "db-arch.couoacqalfwt.us-east-2.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "postgres"
  DB_SCHEMA: "public"
  DB_DRIVER: "postgres"
  NO_AZ: "true"
  KAFKA_USER: "admin"
  KAFKA_PASSWORD: "admin"
  KAFKA_PROTOCOL: "PLAINTEXT"
  KAFKA_MECHANISM: "PLAINTEXT"
  KAFKA_CLIENT_ID: "GO-WORKER-CREDIT"
  KAFKA_GROUP_ID: "GROUP-WORKER-CREDIT-01"
  KAFKA_BROKER_1: "b-1.mskarchtest02.9vkh4b.c3.kafka.us-east-2.amazonaws.com:9092"
  KAFKA_BROKER_2: "b-2.mskarchtest02.9vkh4b.c3.kafka.us-east-2.amazonaws.com:9092"
  KAFKA_BROKER_3: ""
  KAFKA_PARTITION: "6"
  KAFKA_REPLICATION: "2"
  TOPICS: "topic.credit"
  #SERVER_URL_DOMAIN: "http://svc-go-credit.test-a.svc.cluster.local:5001"
  SERVER_URL_DOMAIN: "https://vpce.global.dev.caradhras.io/pv"
  X_APIGW_API_ID: "cy5ry2263h"